version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/libfintx/libfintx.csproj --verbosity m
build_script:
  - cmd: dotnet build ./src/libfintx/libfintx.csproj
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/libfintx.Tests/libfintx.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test src/libfintx.Tests